name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - component: 'backend'
            subcomponent: 'DirectX'
          - component: 'backend'
            subcomponent: 'Metal'
          - component: 'backend'
            subcomponent: 'Opengl'
          - component: 'backend'
            subcomponent: 'Mojo'
          - component: 'translator'
            subcomponent: 'none'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        if [ "${{ matrix.subcomponent }}" == "none" ]; then
          pytest tests/test_translator
        else
          pytest tests/test_backend/test_${{ matrix.subcomponent }}
        fi
